data:
  dataset_configs:
    bboxed_dataset_urban_cars:

            # train_transform: copy@data/dataset_configs/bboxed_dataset_only_bbox/train_transform
            train_transform: null

            eval_transform:
                from_class-Normalize:
                  class: torchvision.transforms.Normalize
                  kwargs:
                    mean:
                    - 0.485
                    - 0.456
                    - 0.406
                    std:
                    - 0.229
                    - 0.224
                    - 0.225
                from_class-ToTensor:
                  class: torchvision.transforms.ToTensor
                transforms_list:
                  - from_class-ToTensor
                  - from_class-Normalize

            train_val_split: 0.0

            csv_path: ./data/csvs/cropformer/source_urban_cars_cropformer.parquet
            dataset_task: classification
            label_converter: "./data/datasets/UrbanCars/label_converter.pt"
            foreground_keyword: null
