params:
  random_seed: 42
is_python: True

exec_path: <p>
conda_env: ./envs/occam

kwargs:
  "model_id": dinosaur_base_patch14_518_topk3.coco_dv2_ft_s7_300k+10k
  "input_folder": <p>
  "output": <p>


logging:
  gdrive_storage_folder: null
  use_wandb: false
